apply plugin: 'com.android.library'

android {
    namespace = "org.opencv"
    compileSdk 34

    buildFeatures {
        aidl = true
    }

    defaultConfig {
        minSdk 21
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.txt'
        }
    }
    lint {
        targetSdk 29
    }
    testOptions {
        targetSdk 29
    }
}
